"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ModuloWifi_1 = require("./ModuloWifi");
var SmartHeladera_1 = require("./SmartHeladera");
var modulo = new ModuloWifi_1.ModuloWifi(300, 20);
var smartH = new SmartHeladera_1.SmartHeladera("Sanyo", "2025", 10, modulo, "Domestica");
console.log(smartH);
smartH.Encender();
smartH.setMarca("Philco");
smartH.setModelo("2024");
smartH.setTemperatura(0);
smartH.conectarInternet("Publica");
modulo.setVelocidadMbps(500);
modulo.setFrecuenciaGHz(30);
console.log(smartH);
smartH.apagar();
console.log(smartH);
